### ISSUE TITLE
write a program in python for natural numbers?

### ISSUE THREAD

**Issue by challapriyadarshini** [challapriyadarshini/challapriyadarshini-CSA1093#2]
natural numbers up to 10

**Comment by Satyahyndavi** [comment]
> natural numbers up to 10
natural_numbers = list(range(1, 11))
print(natural_numbers)

**Comment by Satyahyndavi** [comment]
> natural numbers up to 10
natural_numbers = list(range(1, 11))
print(natural_numbers)
